version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379
  db:
    image: postgres
    env_file: .env
    ports:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: ./source/
    image: my_home_control
    volumes:
      - gem_cache:/usr/local/bundle/gems
      - app_logs:/app/log
      - app_public:/app/public
    ports:
      - 3000:3000
    env_file: .env
    environment:
#      RAILS_SERVE_STATIC_FILES: 1
      REDIS_URL: redis
      DATABASE_HOST: db
      RAILS_ENV: production
    depends_on:
      - db
      - redis
    command: start
volumes:
  app_public:
  db_data:
  gem_cache:

# after_build
# docker-compose run app bundle exec rake db:create db:setup
